In [41]:
import numpy as np

## 1.Datatypes and Attributes

In [42]:
# NumPy's main datatype is 'ndarray' (n dimensional array)

In [43]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [44]:
type(a1)

numpy.ndarray

In [45]:
a2 = np.array([[1.2,2,3],
                [4,5,6]])
a2

array([[1.2, 2. , 3. ],
       [4. , 5. , 6. ]])

In [46]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               
               [[11,12,13],
               [14,15,16],
               [17,18,19]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [47]:
a1.shape
# this tells the (no. of rows, column, no. of across)

(3,)

In [48]:
a2.shape

(2, 3)

In [49]:
a3.shape

(2, 3, 3)

In [50]:
# Tells about the no. of dimensions
a1.ndim

1

In [51]:
a2.ndim

2

In [52]:
a3.ndim

3

In [53]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [54]:
a1.size, a2.size, a3.size
# Tells the no. of elements in an array

(3, 6, 18)

In [55]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [56]:
a2

array([[1.2, 2. , 3. ],
       [4. , 5. , 6. ]])

In [57]:
# Creating a dataframe from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.2  2.0  3.0
1  4.0  5.0  6.0

## 2.Creating Arrays

In [59]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [60]:
sample_array.dtype

dtype('int32')